CREATE TABLE data_group (
    group_id NUMBER
         GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 INCREMENT BY 1 )
    ,  group_code NVARCHAR2(25) NOT NULL
    ,  group_name NVARCHAR2(225) NOT NULL
    ,  group_function_code NVARCHAR2(25) NOT NULL
    ,  active NUMBER(1,0) NOT NULL
    ,  note NVARCHAR2(2000) 
    , PRIMARY KEY ( group_code )
);

CREATE TABLE data_feature (
    feature_id NUMBER 
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 INCREMENT BY 1 )
    ,  feature_code NVARCHAR2(25) NOT NULL
    ,  feature_name NVARCHAR2(225) NOT NULL
    ,  icon NVARCHAR2(255)
    , PRIMARY KEY ( feature_code )
);

CREATE TABLE data_group_permission (
     group_id NUMBER
         GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 INCREMENT BY 1 )
    ,  group_code NVARCHAR2(25) NOT NULL
    ,  feature_code NVARCHAR2(25) NOT NULL
    , PRIMARY KEY ( group_id )
    , CONSTRAINT FK_GROUP FOREIGN KEY (group_code) REFERENCES data_group(group_code)
    , CONSTRAINT FK_FEATURE FOREIGN KEY (feature_code) REFERENCES data_feature(feature_code)
);

CREATE TABLE data_user (
    user_id NUMBER
         GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 INCREMENT BY 1 )
    ,  user_code NVARCHAR2(25) NOT NULL
    ,  user_name NVARCHAR2(225) NOT NULL
    ,  user_pass NVARCHAR2(2000) NOT NULL
    , PRIMARY KEY ( user_code )
);

ALTER TABLE data_user ADD active NUMBER(1,0) NOT NULL;
ALTER TABLE data_feature ADD active NUMBER(1,0) NOT NULL;

CREATE TABLE data_role (
    role_id NUMBER
         GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 INCREMENT BY 1 )
    ,  feature_code NVARCHAR2(25) NOT NULL
    ,  user_code NVARCHAR2(25) NOT NULL
    , PRIMARY KEY ( role_id )
    , CONSTRAINT FK_USER_ROLE FOREIGN KEY (user_code) REFERENCES data_user(user_code)
    , CONSTRAINT FK_FEATURE_ROLE FOREIGN KEY (feature_code) REFERENCES data_feature(feature_code)
);

CREATE TABLE data_user_group(
    usergroup_id NUMBER
         GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 INCREMENT BY 1 )
    ,  user_code NVARCHAR2(25) NOT NULL
    ,  group_code NVARCHAR2(25) NOT NULL
    , PRIMARY KEY ( usergroup_id )
    , CONSTRAINT FK_USERGROUP_USER FOREIGN KEY (user_code) REFERENCES data_user(user_code)
    , CONSTRAINT FK_USERGROUP_GROUP FOREIGN KEY (group_code) REFERENCES data_group(group_code)
);

COMMIT;