CREATE TABLE product (
    product_id    NUMBER
         GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 INCREMENT BY 1 )
    NOT NULL,
    product_name  VARCHAR2(100) NOT NULL,
    product_code  VARCHAR2(100),
    release_date  DATE,
    description   VARCHAR2(100),
    price         NUMBER,
    star_rating  NUMBER,
    image_url     VARCHAR2(100),
    PRIMARY KEY ( product_id )
);

ALTER TABLE product MODIFY
    description VARCHAR2(4000);

ALTER TABLE product MODIFY
    product_name VARCHAR2(4000);
    
ALTER TABLE product MODIFY
    product_code VARCHAR2(4000);
    
ALTER TABLE product MODIFY
    image_url VARCHAR2(4000);
    
ALTER TABLE product MODIFY
    product_type VARCHAR2(4000);

ALTER TABLE product MODIFY
    release_date DATE;
--DROP TABLE product;

CREATE TABLE hibernate_sequence (
    next_val NUMBER
);

--DROP TABLE hibernate_sequence;

select * from product;

INSERT INTO product (
    product_name,
    product_code,
    release_date,
    description,
    price,
    star_rating,
    image_url
) VALUES (
    'Hammer',
    'HMR-0001',
    TO_DATE('07-16-2021', 'MM-dd-yyyy'),
    'Curved claw steel hammer',
    16.7,
    3.68,
    'assets/images/hammer.png'
);

INSERT INTO product (
    product_name,
    product_code,
    release_date,
    description,
    price,
    star_rating,
    image_url
) VALUES (
    'Saw',
    'SAW-0002',
    TO_DATE('09-09-2021', 'MM-dd-yyyy'),
    'Steel Saw',
    9.9,
    3.36,
    'assets/images/saw.png'
);

INSERT INTO product (
    product_name,
    product_code,
    release_date,
    description,
    price,
    star_rating,
    image_url
) VALUES (
    'Garden Cart',
    'GCT-0003',
    TO_DATE('07-09-2021', 'MM-dd-yyyy'),
    '15 Gallon Steel Cart',
    7.9,
    3.77,
    'assets/images/garden_cart.png'
);

INSERT INTO product (
    product_name,
    product_code,
    release_date,
    description,
    price,
    star_rating,
    image_url
) VALUES (
    'Leaf Rake',
    'LRK-0004',
    TO_DATE('09-16-2021', 'MM-dd-yyyy'),
    'Steel Rake',
    16.9,
    3.46,
    'assets/images/leaf_rake.png'
);

INSERT INTO product (
    product_name,
    product_code,
    release_date,
    description,
    price,
    star_rating,
    image_url
) VALUES (
    'Xbox Controller',
    'XBC-0005',
    TO_DATE('11-20-2021', 'MM-dd-yyyy'),
    'New Version and New Features',
    20.11,
    3.68,
    'assets/images/xbox-controller.png'
);

INSERT INTO product (
    product_name,
    product_code,
    release_date,
    description,
    price,
    star_rating,
    image_url
) VALUES (
    'Laptop Dell',
    'DEL-0006',
    TO_DATE('11-10-2021', 'MM-dd-yyyy'),
    'Dell Vostro 3458',
    198.26,
    4.54,
    'assets/images/laptop.png'
);

INSERT INTO product (
    product_name,
    product_code,
    release_date,
    description,
    price,
    star_rating,
    image_url
) VALUES (
    'Mouse',
    'MOU-0007',
    TO_DATE('10-16-2021', 'MM-dd-yyyy'),
    'Logitech Mouse Silent M331',
    52.75,
    4.43,
    'assets/images/mouse.png'
);

INSERT INTO product (
    product_name,
    product_code,
    release_date,
    description,
    price,
    star_rating,
    image_url
) VALUES (
    'KeyBoard',
    'KBD-0008',
    TO_DATE('08-08-2021', 'MM-dd-yyyy'),
    'Silent Switch, Alien Gaming',
    105.85,
    1.84,
    'assets/images/keyboard.png'
);

INSERT INTO product (
    product_name,
    product_code,
    release_date,
    description,
    price,
    star_rating,
    image_url
) VALUES (
    'Apple Iphone',
    'AIP-0009',
    TO_DATE('09-10-2021', 'MM-dd-yyyy'),
    'Iphone 13, New Generation',
    1185.90,
    4.75,
    'assets/images/iphone.png'
);

INSERT INTO product (
    product_name,
    product_code,
    release_date,
    description,
    price,
    star_rating,
    image_url
) VALUES (
    'Light',
    'AIP-0009',
    TO_DATE('09-10-2021', 'MM-dd-yyyy'),
    'New Generation, More Brightness',
    87.25,
    3.45,
    'assets/images/light.png'
);

INSERT INTO product (
    product_name,
    product_code,
    release_date,
    description,
    price,
    star_rating,
    image_url
) VALUES (
    'RAM',
    'RAM-0011',
    TO_DATE('07-05-2021', 'MM-dd-yyyy'),
    'RAM 8 GB Gforce',
    35.9,
    3.78,
    'assets/images/ram.png'
);

INSERT INTO hibernate_sequence ( next_val ) VALUES ( 11 );

COMMIT;
